Website_MiniF4/MiniF4Store/MiniF4Store/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using MiniF4Store.Models;
using System.Web.Mail;

namespace MiniF4Store.Controllers
{
    public class TaiKhoanController : Controller
    {
        QL_BachHoaDataContext db = new QL_BachHoaDataContext();
        #region Đăng Nhập Tài Khoản
        [HttpGet]
        public ActionResult DangNhap()
        {            
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult DangNhap(FormCollection userlog)
        {
            string userMail = userlog["userMail"].ToString();
            string password = userlog["password"].ToString();
            if (String.IsNullOrEmpty(userMail))
            {
                ViewData["Loi1"] = "Tài khoản không được bỏ trống!";
            }
            if (String.IsNullOrEmpty(password))
            {
                ViewData["Loi2"] = "Mật khẩu không được bỏ trống!";
            }
            if (!String.IsNullOrEmpty(userMail) && !String.IsNullOrEmpty(password))
            {                
                var admin = db.NHANVIENs.SingleOrDefault(tk => tk.TAIKHOAN.Equals(userMail) && tk.MATKHAU.Equals(password));
                var check = db.KHACHHANGs.SingleOrDefault(t => t.EMAIL.Equals(userMail) && t.MATKHAU.Equals(password));

                if (check != null)
                {
                    Session["use"] = check;
                    return RedirectToAction("Index", "Home");
                }
                else if (admin != null)
                {
                    Session["admin"] = admin;
                    return RedirectToAction("Trang_chu", "Admin");
                }
                else
                {
                    ViewBag.Fail = "Tai khoan hoac mat khau khong chinh xac!";
                    return View("DangNhap");
                }
            }
            else
            {
                ViewBag.Fail = "Vui long nhap day du thong tin!";
                return View("DangNhap");
            }
        }
        #endregion

        #region Đăng Xuất
        public ActionResult DangXuat()
        {            
            Session["use"] = null;
            Session["GioHang"] = null;
            ViewBag.TongSoLuongLoaiMatHang = 0;
            return RedirectToAction("Index", "Home");            
        }
        #endregion

        #region Đăng Ký Tài Khoản
        //Kiểm tra độ mạnh yếu của mật khẩu khi dang ky
        public static bool IsStrongPassword(string password)
        {
            if (!string.IsNullOrEmpty(password))
            {
            // Kiểm tra độ dài
            if (password.Length < 8)
            {
                return false;
            }

            // Kiểm tra xem có ít nhất một chữ cái viết hoa
            if (!password.Any(char.IsUpper))
            {
                return false;
            }

            // Kiểm tra xem có ít nhất một chữ cái viết thường
            if (!password.Any(char.IsLower))
            {
                return false;
            }

            // Kiểm tra xem có ít nhất một chữ số
            if (!password.Any(char.IsDigit))
            {
                return false;
            }

            // Kiểm tra xem có ít nhất một ký tự đặc biệt
            if (!password.Any(ch => !char.IsLetterOrDigit(ch)))
            {
                return false;
                }

            }

            return true;
        }
        // Hàm để tạo chuỗi ngẫu nhiên
        private string GenerateRandomString(int length)
        {
            string chars = "0123456789";
            Random random = new Random();
            char[] randomString = new char[length];

            for (int i = 0; i < length; i++)
            {
                randomString[i] = chars[random.Next(chars.Length)];
            }

            return new string(randomString);
        }
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(DangKyModel dkm)
        {
            if (db.KHACHHANGs.Any(x => x.SDT_KH == dkm.PhoneNumber))
            {
                ModelState.AddModelError("PhoneNumber", "Số điện thoại này đã được đăng ký!. Vui lòng chọn số điện thoại khác.");
            }
            if (!string.IsNullOrEmpty(dkm.PhoneNumber))
            {
                if (dkm.PhoneNumber.Length != 10)
                {
                    ModelState.AddModelError("PhoneNumber", "Số điện thoại không hợp lệ!");
                }
                else if (!dkm.PhoneNumber.All(char.IsDigit))
                {
                    ModelState.AddModelError("PhoneNumber", "Đây không phải là số điện thoại!");
                }
            }
            if (!string.IsNullOrEmpty(dkm.SDT_NHANHANG))
            {
                if (dkm.SDT_NHANHANG.Length != 10)
                {
                    ModelState.AddModelError("SDT_NHANHANG", "Số điện thoại không hợp lệ!");
                }
                else if (!dkm.SDT_NHANHANG.All(char.IsDigit))
                {
                    ModelState.AddModelError("SDT_NHANHANG", "Đây không phải là số điện thoại!");
                }
            }
            if (string.IsNullOrEmpty(dkm.Email))
            {
                ModelState.AddModelError("Email", "Email không được bỏ trống!.");
            }
            else
            {
                string email = dkm.Email.Trim();
                if (!string.IsNullOrEmpty(email))
                {
                    if (!Regex.IsMatch(email, @"^[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$"))
                    {
                        ModelState.AddModelError("Email", "Định dạng Email không đúng.");
                    }
                }
            }
            if (!IsStrongPassword(dkm.Password))
            {
                ModelState.AddModelError("Password", "Mật khẩu không đủ mạnh. Yêu cầu ít nhất 8 ký tự, chứa chữ hoa, chữ thường, số và ký tự đặc biệt!.");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    KHACHHANG khachhang = new KHACHHANG();
                    khachhang.EMAIL = dkm.Email;
                    khachhang.MATKHAU = dkm.Password;
                    khachhang.TENKH = dkm.Name;
                    khachhang.SDT_KH = dkm.PhoneNumber;
                    khachhang.DIACHI = dkm.Address;
                    khachhang.SDT_NHANHANG = dkm.SDT_NHANHANG;
                    khachhang.TEN_NHANHANG = dkm.TEN_NHANHANG;
                    khachhang.DIACHI_NHANHANG = dkm.DIACHI_NHANHANG;
                    //khachhang.SDT_NHANHANG = dkm.PhoneNumber;
                    //khachhang.TEN_NHANHANG = dkm.Name;
                    //khachhang.DIACHI_NHANHANG = dkm.Address;
                    //----------------------------------------------------------
                    System.Net.Mail.MailMessage mm = new System.Net.Mail.MailMessage("truongdat20012002@gmail.com",dkm.Email);
                    mm.Subject = "MINIF4 Store - Xác nhận OTP đăng ký tài khoản";
                    // Tạo một chuỗi ngẫu nhiên
                    string randomString = GenerateRandomString(6);
                    mm.Body ="Mã OTP: " + randomString;
                    mm.IsBodyHtml = false;

                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;

                    NetworkCredential nc = new NetworkCredential("truongdat20012002@gmail.com", "owxpyxethkdfzkua");
                    smtp.UseDefaultCredentials = true;
                    smtp.Credentials = nc;
                    smtp.Send(mm);
                    
                    // Insert vào cơ sở dữ liệu
                    khachhang.OTP = randomString;
                    db.KHACHHANGs.InsertOnSubmit(khachhang);
                    db.SubmitChanges();
                    //------------------------------------------------
                    ViewBag.guiOTP = "Đã gửi OTP đến hộp thư của bạn!";
                    ViewBag.kt = true;
                    ViewBag.maOTP = randomString;
                    return View("maOTP");
                }
                catch (Exception ex)
                {
                    ViewBag.kq = "Lỗi rồi.";
                    return View();
                }
            }
            else
            {
                ViewBag.kq = "Đăng ký tài khoản thất bại. Vui lòng thử lại!";
                return View();
            }
        }
        #endregion

        #region Thông Tin Tài Khoản
        public ActionResult Profile(string id_kh)
        {
            if (string.IsNullOrEmpty(id_kh))
            {
                return RedirectToAction("Index","Home");
            }

            var khachhang = db.KHACHHANGs.SingleOrDefault(s => s.SDT_KH.Equals(id_kh));
            
            if (khachhang != null)
            {
                return View(khachhang);
            }

            return HttpNotFound();
        }
        #endregion

        #region Cập Nhật Thông Tin Tài Khoản
        [HttpGet]
        public ActionResult EditProfile(string id_kh)
        {
            if (string.IsNullOrEmpty(id_kh))
            {
                return RedirectToAction("Index", "Home");
            }

            var khachhang = db.KHACHHANGs.SingleOrDefault(s => s.SDT_KH.Equals(id_kh));

            if (khachhang != null)
            {
                return View(khachhang);
            }

            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult EditProfile(KHACHHANG khachhang)
        {
            if (string.IsNullOrEmpty(khachhang.EMAIL) || string.IsNullOrEmpty(khachhang.DIACHI) ||

Website_MiniF4/MiniF4Store/MiniF4Store/Views/TaiKhoan/DangKy.cshtml
@model MiniF4Store.Models.DangKyModel

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<h2 style="text-align:center">ĐĂNG KÝ</h2>
<section class="container">
    @using (Html.BeginForm("DangKy", "TaiKhoan", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @ViewBag.kq
        <div class="form-horizontal">
            <hr />   
            <h4>Đăng Ký Thông Tin Tài Khoản</h4> 
            <br />        
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-user"></i>@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.Email, new { id = "Email", placeholder = "Nhập Email của bạn...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.Email)</p>
                </div>
            </div>

            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-lock"></i>@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.PasswordFor(model => model.Password, new { id = "password", placeholder = "Nhập mật khẩu...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.Password)</p>
                </div>
            </div>
            &nbsp;&nbsp;<input type="checkbox" id="showPassword"> Hiện mật khẩu
            <br />
            <br />
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-lock"></i>@Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.PasswordFor(model => model.ConfirmPassword, new {id="repass", placeholder = "Xác nhận lại mật khẩu...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.ConfirmPassword)</p>
                </div>
            </div>
            &nbsp;&nbsp;<input type="checkbox" id="repassword"> Hiện mật khẩu
            <br />
            <br />
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-newspaper-o"></i>@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.Name, new { id = "Name", placeholder = "Nhập họ tên...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.Name)</p>
                </div>
            </div>

            <div class="form-group">
                &nbsp;<i class="fa fa-address-book-o"></i>@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.Address, new { id = "Address", placeholder = "Nhập địa chỉ...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.Address)</p>
                </div>
            </div>

            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-phone"></i>&nbsp;@Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.PhoneNumber, new { id = "PhoneNumber", placeholder = "Nhập số điện thoại...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.PhoneNumber)</p>
                </div>
            </div>
            <hr />
            <h4>Đăng Ký Thông Tin Nhận Hàng</h4>
            <br />
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-newspaper-o"></i>&nbsp;@Html.LabelFor(model => model.TEN_NHANHANG, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.TEN_NHANHANG, new {placeholder = "Nhập họ tên người nhận hàng...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.TEN_NHANHANG)</p>
                </div>
            </div>
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                <i class="fa fa-phone"></i>&nbsp;@Html.LabelFor(model => model.SDT_NHANHANG, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.SDT_NHANHANG, new {placeholder = "Nhập số điện thoại nhận hàng...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.SDT_NHANHANG)</p>
                </div>
            </div>
            <div class="form-group">
                <label for="Email" style="color: red;">*</label>
                &nbsp;<i class="fa fa-address-book-o"></i>@Html.LabelFor(model => model.DIACHI_NHANHANG, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.DIACHI_NHANHANG, new { placeholder = "Nhập địa chỉ nhận hàng...", @class = "form-control" })
                    <p style="color:red;">@Html.ValidationMessageFor(model => model.DIACHI_NHANHANG)</p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="a" type="submit" value="Đăng ký" class="site-btn" />
                </div>
            </div>
        </div>
    }
    <a style="color: #80ac3c;" href="/TaiKhoan/DangNhap">[Bạn đã có tài khoản?] Đăng nhập ngay</a>
    
    <br />
    <hr />
    <br />
</section>
<script>
    var kqMessage = '@ViewBag.Message';
    if (kqMessage) {
        alert(kqMessage);
    }
    var passwordField = document.getElementById("password");
    var showPasswordCheckbox = document.getElementById("showPassword");
    showPasswordCheckbox.addEventListener("change", function () {
        passwordField.type = this.checked ? "text" : "password";
    });
    var passwordField2 = document.getElementById("repass");
    var showPasswordCheckbox2 = document.getElementById("repassword");
    showPasswordCheckbox2.addEventListener("change", function () {
        passwordField2.type = this.checked ? "text" : "password";
    });
</script>

Website_MiniF4/MiniF4Store/MiniF4Store/Views/TaiKhoan/DangNhap.cshtml
@model MiniF4Store.Models.DangNhapModel

@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<style>
    .custom-dialog {
        position: fixed;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        border:1px solid black;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        padding: 30px; /* Tăng giá trị padding để làm cho hộp thoại lớn hơn */
        z-index: 1000;
        max-width: 600px; /* Tăng giá trị max-width để làm cho hộp thoại lớn hơn */
        text-align: center;}
    .custom-dialog p {
        font-size: 18px;
        margin-bottom: 10px;
        color:black;}
    .custom-dialog-close {
        background: #333;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        cursor: pointer;}
    .custom-dialog-close:hover {
        background: #555;}
</style>
<h2 style="text-align:center">Đăng nhập tài khoản</h2>
@if (ViewBag.thanhcong != null)
{
    if (ViewBag.thanhcong == true)
    {
        <div class="alert alert-success">@ViewBag.thongbao</div>
    }
}
@if (ViewBag.ktra != null)
{
    if (ViewBag.ktra == true)
    {
        <div class="alert alert-success">@ViewBag.thanhcongnhe</div>
    }
}
<section class="container">
    @using (Html.BeginForm("DangNhap", "TaiKhoan", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <label for="Email" style="color: red;">*</label>
            <i class="fa fa-user"></i>@Html.LabelFor(model => model.userMail, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <p style="color:red;">@ViewData["Loi1"]</p>
                @Html.TextBoxFor(model => model.userMail, new { placeholder = "Nhập tài khoản...", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.userMail)
            </div>
            <p style="color:red;">@ViewBag.FailEmail</p>
        </div>

        <div class="form-group">
            <label for="Email" style="color: red;">*</label>
            <i class="fa fa-lock"></i>@Html.LabelFor(model => model.password, new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <p style="color:red">@ViewData["Loi2"]</p>
                @Html.PasswordFor(model => model.password, new { id = "password", placeholder = "Nhập mật khẩu...", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.password)
            </div>
            <p style="color:red;">@ViewBag.FailPass</p>
        </div>
        <input type="checkbox" id="showPassword"> Hiện mật khẩu        
        <br />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="đăng nhập" class="site-btn" />
            </div>
        </div>
    </div>
    }
    <a style="color: #80ac3c;" href="/TaiKhoan/DangKy">[Bạn chưa có tài khoản?] Đăng ký ngay</a>
    <br />
    <hr />
    <br />
</section>
<script>
    var flashing = false;
    function showDialog(message) {
    var dialog = document.createElement("div");
    dialog.className = "custom-dialog";
    var messageElement = document.createElement("p");
    messageElement.textContent = message;
    var closeButton = document.createElement("button");
    closeButton.textContent = "Đóng";
    closeButton.className = "custom-dialog-close";
    closeButton.addEventListener("click", function () {
        document.body.removeChild(dialog);
    });
    dialog.appendChild(messageElement);
    dialog.appendChild(closeButton);
    document.body.appendChild(dialog);
    flashing = true;
    var backgroundColors = ["white", "#80ac3c"];
    var colorIndex = 0;
    function flashBackground() {
        if (flashing) {
            dialog.style.background = backgroundColors[colorIndex];
            colorIndex = 1 - colorIndex;
            setTimeout(flashBackground, 200);
        }
    }
    flashBackground();
    setTimeout(function() {
        flashing = false;
        document.body.removeChild(dialog);
    }, 10000);
    }
    var passwordField = document.getElementById("password");
    var showPasswordCheckbox = document.getElementById("showPassword");
    showPasswordCheckbox.addEventListener("change", function () {
        passwordField.type = this.checked ? "text" : "password";
    });
var kqMessage = '@ViewBag.Fail';
if (kqMessage) {
    showDialog(kqMessage);
}
</script>

Website_MiniF4/MiniF4Store/MiniF4Store/Views/TaiKhoan/EditProfile.cshtml
@model MiniF4Store.Models.KHACHHANG

@{
    ViewBag.Title = "EditProfile";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@if (ViewBag.thanhcong == true)
{
    <div class="alert alert-success">@ViewBag.thongbao</div>
}
<h2 style="text-align:center">Chỉnh sửa tài khoản</h2>
<section class="container">
    @using (Html.BeginForm("EditProfile", "TaiKhoan", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            <h4>Chỉnh sửa thông tin tài khoản</h4>
            <br />
            <p style="color:red;">@ViewBag.ErrorMessage@ViewBag.Message</p>
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.SDT_KH)
            <div class="form-group">
                <b>Họ tên khách hàng</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.TENKH, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TENKH)
                </div>
            </div>

            <div class="form-group">
                <b>Địa chỉ</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.DIACHI, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DIACHI)
                </div>
            </div>

            <div class="form-group">
                <b>Email</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.EMAIL, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EMAIL)
                </div>
            </div>

            <div class="form-group">
                <b>Mật khẩu</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.MATKHAU, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MATKHAU)
                </div>
            </div>
            <h4>Chỉnh sửa thông tin nhận hàng</h4>
            <br />
            <div class="form-group">
                <b>Người nhận hàng</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.TEN_NHANHANG, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TEN_NHANHANG)
                </div>
            </div>
            <div class="form-group">
                <b>Số điện thoại nhận hàng</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.SDT_NHANHANG, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SDT_NHANHANG)
                </div>
            </div>
            <div class="form-group">
                <b>Địa chỉ nhận hàng</b>
                <div class="col-md-12">
                    @Html.TextBoxFor(model => model.DIACHI_NHANHANG, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DIACHI_NHANHANG)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="site-btn" />
                </div>
            </div>
        </div>
    }
    <a style="color: #80ac3c;" href="/TaiKhoan/Profile">Quay lại</a>
    <br />
    <hr />
    <br />
</section>
<script>
    var kqMessage = '@ViewBag.thongbao';
    if (kqMessage) {
        alert(kqMessage);
    }
</script>

Website_MiniF4/MiniF4Store/MiniF4Store/Views/TaiKhoan/Profile.cshtml
@model MiniF4Store.Models.KHACHHANG

@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 style="text-align: center;">Thông tin khách hàng</h2>
<section class="container">
    <hr />
    <dl class="form-horizontal">
        <dt>
            Họ và tên
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TENKH)
        </dd>

        <dt>
            Địa chỉ
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DIACHI)
        </dd>

        <dt>
            Email
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            Mật khẩu
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MATKHAU)
        </dd>

        <dt>
            Số điện thoại
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SDT_KH)
        </dd>
    </dl>
    <a style="color: #80ac3c;" href="@Url.Action("EditProfile", "TaiKhoan", new { id_kh = Model.SDT_KH })">Chỉnh sửa thông tin tài khoản</a>
    <br />
    <hr />
    <br />
</section>

Website_MiniF4/MiniF4Store/MiniF4Store/Views/TaiKhoan/maOTP.cshtml
@model MiniF4Store.Models.OTP

@{
    ViewBag.Title = "maOTP";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2 style="text-align:center;">Xác nhận OTP</h2>
@if (ViewBag.kt != null)
{
    if (ViewBag.kt == true)
    {
        <div class="alert alert-success">@ViewBag.guiOTP</div>
    }
}
<section class="container">
    @using (Html.BeginForm("maOTP", "TaiKhoan", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @if (ViewBag.ktra == true)
            {
                <a href="/TaiKhoan/DangNhap">Dang nhap ngay</a>
            }
            @Html.ValidationSummary(true)
            <div class="form-group">
                <h4>Nhập mã OTP đã gửi vào hộp thư Email của bạn!</h4>
                <div class="col-md-12">
                    <p style="color:red;">@ViewData["Fail"]</p>
                    @Html.TextBoxFor(model => model.maOTP, new { placeholder = "Nhập OTP....", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.maOTP)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Xác nhận OTP" class="site-btn" />
                </div>
            </div>
        </div>
    }
</section>